import assert from 'node:assert/strict';
import { dirname, join } from 'node:path';
import { cli } from '../src/cli.ts';
import type { CLIOptions, Shell } from '../src/shared.ts';
import { assetCompletions, writeInstall } from './fixtures.ts';

const FAKE_MISE = `#!/bin/sh
printf '%s|%s\\n' "$PWD" "$*" >> "$FAKE_MISE_LOG"
case "$1" in
  --version) echo "\${FAKE_MISE_VERSION:-2026.9.17} macos-arm64 (2026-09-29)" ;;
  ls) cat "$FAKE_MISE_LS" ;;
  x)
    shift
    specs=''
    while [ "$#" -gt 0 ] && [ "$1" != '--' ]; do specs="$specs $1"; shift; done
    shift
    printf '#compdef %s\\n# generated by%s: %s\\n' "$1" "$specs" "$*"
    ;;
  *) exit 1 ;;
esac
`;

interface ToolFixture {
  version: string;
  active?: boolean;
  installed?: boolean;
}

const exists = async (path: string) => {
  try {
    await Deno.lstat(path);
    return true;
  } catch {
    return false;
  }
};

const harness = async () => {
  const root = await Deno.makeTempDir({ prefix: 'msc-cli-' });
  const bin = join(root, 'bin');
  await Deno.mkdir(bin);
  await Deno.writeTextFile(join(bin, 'mise'), FAKE_MISE);
  await Deno.chmod(join(bin, 'mise'), 0o755);

  const env: Record<string, string> = {
    PATH: `${bin}:${Deno.env.get('PATH')}`,
    FAKE_MISE_LOG: join(root, 'mise.log'),
    FAKE_MISE_LS: join(root, 'ls.json'),
  };
  const saved = Object.fromEntries(
    [...Object.keys(env), 'FAKE_MISE_VERSION'].map((k) => [
      k,
      Deno.env.get(k),
    ]),
  );
  for (const [k, v] of Object.entries(env)) {
    Deno.env.set(k, v);
  }

  const output: string[] = [];
  const original = { log: console.log, warn: console.warn };
  console.log = (...args: unknown[]) => output.push(args.join(' '));
  console.warn = (...args: unknown[]) => output.push(args.join(' '));

  const dataDir = join(root, 'data', 'mise-completions');
  const h = {
    root,
    statePath: join(dataDir, '.state.json'),
    out: (shell: Shell) => join(dataDir, shell),
    file: (shell: Shell, name: string) => join(dataDir, shell, name),
    install: (name: string) => join(root, 'installs', name),

    async tools(tools: Record<string, ToolFixture | ToolFixture[]>) {
      const json: Record<string, unknown[]> = {};
      for (const [name, value] of Object.entries(tools)) {
        json[name] = [value].flat().map((t) => ({
          version: t.version,
          requested_version: 'latest',
          install_path: join(h.install(name.replaceAll('/', '-')), t.version),
          installed: t.installed ?? true,
          active: t.active ?? true,
        }));
        for (const t of [value].flat()) {
          await Deno.mkdir(join(h.install(name.replaceAll('/', '-')), t.version), {
            recursive: true,
          });
        }
      }
      await Deno.writeTextFile(env.FAKE_MISE_LS!, JSON.stringify(json));
    },

    /** Output lines printed during the run. */
    async run(opts: Partial<CLIOptions> = {}): Promise<string> {
      const start = output.length;
      const shell = opts.shell ?? 'zsh';
      await cli({
        statePath: h.statePath,
        completionsPath: h.out(shell),
        registryPath: join(root, 'no-user-registry.ts'),
        verbose: true,
        ...opts,
        shell,
      });
      return output.slice(start).join('\n');
    },

    /** mise invocations since the last call, as `{ cwd, args }`. */
    async calls(): Promise<{ cwd: string; args: string }[]> {
      const text = await Deno.readTextFile(env.FAKE_MISE_LOG!).catch(() => '');
      await Deno.writeTextFile(env.FAKE_MISE_LOG!, '');
      return text.split('\n').filter(Boolean).map((line) => {
        const [cwd, args] = line.split('|');
        return { cwd: cwd!, args: args ?? '' };
      });
    },

    async state() {
      return JSON.parse(await Deno.readTextFile(h.statePath));
    },

    async cleanup() {
      console.log = original.log;
      console.warn = original.warn;
      for (const [k, v] of Object.entries(saved)) {
        if (v === undefined) {
          Deno.env.delete(k);
        } else {
          Deno.env.set(k, v);
        }
      }
      await Deno.remove(root, { recursive: true });
    },
  };
  return h;
};

type Harness = Awaited<ReturnType<typeof harness>>;

const test = (name: string, fn: (h: Harness) => Promise<void>) =>
  Deno.test(name, async () => {
    const h = await harness();
    try {
      await fn(h);
    } finally {
      await h.cleanup();
    }
  });

const nativeHk = (h: Harness, version = '2.4.0') =>
  writeInstall(join(h.install('hk'), version), { bins: ['hk'], ...assetCompletions('hk') });

test('native packslip installs skip generation in every shell', async (h) => {
  await h.tools({ hk: { version: '2.4.0' }, deno: { version: '2.1.0' } });
  await nativeHk(h);
  for (const shell of ['zsh', 'bash', 'fish'] as const) {
    assert.match(await h.run({ shell }), /native: 1/);
  }
  const calls = (await h.calls()).map((c) => c.args);
  assert.ok(!calls.some((c) => c.includes('-- hk ')), 'no legacy hk generator ran');
  assert.ok(calls.includes('x deno@2.1.0 -- deno completions zsh'));
  assert.equal(await exists(h.file('zsh', '_hk')), false);
  assert.equal(await exists(h.file('fish', 'hk.fish')), false);
  assert.ok(await exists(h.file('zsh', '_deno')));
  assert.ok(await exists(h.file('fish', 'deno.fish')));
  assert.ok(await exists(h.file('bash', 'deno')));
});

test('shells, destinations, and missing files are tracked independently', async (h) => {
  await h.tools({ deno: { version: '2.1.0' } });
  await h.run({ shell: 'zsh' });
  assert.match(await h.run({ shell: 'fish' }), /updated: 2/);
  const other = join(h.root, 'other');
  assert.match(await h.run({ shell: 'zsh', completionsPath: other }), /updated: 2/);
  assert.ok(await exists(join(other, '_deno')));

  assert.match(await h.run({ shell: 'zsh' }), /updated: 0, skipped: 2/);
  await Deno.remove(h.file('zsh', '_deno'));
  assert.match(await h.run({ shell: 'zsh' }), /updated: 1, skipped: 1/);
  assert.ok(await exists(h.file('zsh', '_deno')));
});

test('provider is reconsidered before the cache; --force never overrides native', async (h) => {
  await h.tools({ hk: { version: '2.4.0' }, usage: { version: '6.12.0' } });
  await h.run();
  const calls = (await h.calls()).map((c) => c.args);
  assert.ok(calls.includes('x hk@2.4.0 usage@6.12.0 -- hk completion zsh'));
  assert.ok(await exists(h.file('zsh', '_hk')));

  await nativeHk(h);
  const out = await h.run({ force: true });
  assert.match(out, /retire hk/);
  assert.match(out, /removed: 1/);
  assert.ok(!(await h.calls()).some((c) => c.args.includes('-- hk ')));
  assert.equal(await exists(h.file('zsh', '_hk')), false);
  assert.equal((await h.state()).outputs[h.file('zsh', '_hk')].provider, 'native');

  await Deno.remove(join(h.install('hk'), '2.4.0', '.mise-packslip.json'));
  await h.run();
  assert.ok(await exists(h.file('zsh', '_hk')), 'switching back regenerates');
});

test('an edited legacy file is preserved at handoff', async (h) => {
  await h.tools({ hk: { version: '2.4.0' } });
  await h.run();
  await Deno.writeTextFile(h.file('zsh', '_hk'), '# edited\n');
  await nativeHk(h);
  assert.match(await h.run(), /_hk changed since it was written; preserved/);
  assert.equal(await Deno.readTextFile(h.file('zsh', '_hk')), '# edited\n');
});

test('needs-attention keeps the legacy completion', async (h) => {
  await h.tools({ hk: { version: '2.4.0' } });
  await writeInstall(join(h.install('hk'), '2.4.0'), {
    bins: ['hk'],
    resources: assetCompletions('hk').resources,
  });
  const out = await h.run();
  assert.match(out, /packslip declares a zsh completion .* keeping legacy completion/);
  assert.match(out, /needs-attention: 1/);
  assert.ok(await exists(h.file('zsh', '_hk')));
});

test('declared generators stay pending and keep the legacy completion', async (h) => {
  await h.tools({ hk: { version: '2.4.0' } });
  await writeInstall(join(h.install('hk'), '2.4.0'), {
    bins: ['hk'],
    resources: [{ kind: 'completion', shells: ['zsh', 'bash', 'fish'], exec: ['hk', '{shell}'] }],
  });
  assert.match(await h.run(), /pending: 1/);
  assert.ok(await exists(h.file('zsh', '_hk')));
  assert.equal((await h.state()).outputs[h.file('zsh', '_hk')].provider, 'legacy');
});

test('files this task never wrote are left alone at handoff', async (h) => {
  await h.tools({ hk: { version: '2.4.0' }, usage: { version: '6.12.0' } });
  await nativeHk(h);
  await writeInstall(join(h.install('usage'), '6.12.0'), {
    bins: ['usage'],
    ...assetCompletions('usage'),
  });
  await Deno.mkdir(h.out('zsh'), { recursive: true });
  await Deno.writeTextFile(h.file('zsh', '_hk'), '# from elsewhere\n');
  await Deno.writeTextFile(join(h.root, 'usage-target'), '# linked\n');
  await Deno.symlink(join(h.root, 'usage-target'), h.file('zsh', '_usage'));

  assert.match(await h.run(), /native: 2/);
  assert.equal(await Deno.readTextFile(h.file('zsh', '_hk')), '# from elsewhere\n');
  assert.ok(await exists(h.file('zsh', '_usage')));
});

test('aliases sharing an output file get one deterministic owner', async (h) => {
  await h.tools({ rg: { version: '15.0.0' }, ripgrep: { version: '15.0.0' } });
  const out = await h.run();
  assert.match(out, /shadow ripgrep: rg owns zsh\/_rg/);
  const calls = (await h.calls()).map((c) => c.args);
  assert.ok(calls.includes('x rg@15.0.0 -- rg --generate complete-zsh'));
  assert.ok(!calls.some((c) => c.includes('ripgrep@')));
  assert.equal((await h.state()).outputs[h.file('zsh', '_rg')].sync_name, 'rg');
});

test('a backend alias writes under the command name in every shell', async (h) => {
  await h.tools({ 'github:railwayapp/cli': { version: '4.10.0' } });
  for (const shell of ['zsh', 'bash', 'fish'] as const) {
    await h.run({ shell });
  }
  const calls = (await h.calls()).map((c) => c.args);
  assert.ok(calls.includes('x github:railwayapp/cli@4.10.0 -- railway completion zsh'));
  assert.ok(await exists(h.file('zsh', '_railway')));
  assert.ok(await exists(h.file('bash', 'railway')));
  assert.ok(await exists(h.file('fish', 'railway.fish')));
  assert.equal(await exists(h.file('zsh', '_cli')), false);
  assert.equal((await h.state()).outputs[h.file('zsh', '_railway')].command, 'railway');

  await h.tools({
    'github:railwayapp/cli': { version: '4.10.0' },
    railway: { version: '4.10.0' },
  });
  assert.match(await h.run(), /shadow github:railwayapp\/cli: railway owns zsh\/_railway/);
  assert.equal((await h.state()).outputs[h.file('zsh', '_railway')].sync_name, 'railway');
});

test('generation uses the installed global selection outside the caller project', async (h) => {
  await h.tools({
    deno: [{ version: '2.0.0', active: false }, { version: '2.1.0' }],
    jj: { version: '0.30.0', installed: false },
  });
  await h.run();
  const calls = await h.calls();
  assert.ok(calls.some((c) => c.args === 'x deno@2.1.0 -- deno completions zsh'));
  assert.ok(!calls.some((c) => c.args.includes('jj')));
  assert.ok(calls.every((c) => c.cwd === '/'));
});

test('reconciliation removes only proven files, never on a failed or empty inventory', async (h) => {
  await h.tools({ deno: { version: '2.1.0' }, jj: { version: '0.30.0' } });
  await h.run();

  await Deno.remove(Deno.env.get('FAKE_MISE_LS')!);
  await h.run();
  await Deno.writeTextFile(Deno.env.get('FAKE_MISE_LS')!, '{}');
  await h.run();
  assert.ok(await exists(h.file('zsh', '_deno')));
  assert.ok(await exists(h.file('zsh', '_jj')));

  await h.tools({ deno: { version: '2.1.0' } });
  assert.match(await h.run(), /remove jj/);
  assert.equal(await exists(h.file('zsh', '_jj')), false);

  await Deno.writeTextFile(h.file('zsh', '_deno'), '# edited\n');
  await h.tools({ jj: { version: '0.30.0' } });
  assert.match(await h.run(), /_deno changed since it was written; preserved/);
  assert.equal(await Deno.readTextFile(h.file('zsh', '_deno')), '# edited\n');
});

test('disabled tools keep their file and record', async (h) => {
  await h.tools({ deno: { version: '2.1.0' } });
  await h.run();
  await h.run({ disabledTools: ['deno'] });
  assert.ok(await exists(h.file('zsh', '_deno')));
  assert.ok((await h.state()).outputs[h.file('zsh', '_deno')]);
});

test('concurrent runs keep every record', async (h) => {
  await h.tools({ deno: { version: '2.1.0' } });
  await Promise.all((['zsh', 'bash', 'fish'] as const).map((shell) => h.run({ shell })));
  const records = Object.values((await h.state()).outputs) as {
    sync_name: string;
    shell: string;
  }[];
  assert.deepEqual(
    records.filter((r) => r.sync_name === 'deno').map((r) => r.shell).sort(),
    ['bash', 'fish', 'zsh'],
  );
});

test('mise older than the tested baseline is refused before anything is written', async (h) => {
  await h.tools({ deno: { version: '2.1.0' } });
  Deno.env.set('FAKE_MISE_VERSION', '2026.9.2');
  await assert.rejects(h.run(), /older than 2026\.9\.17.*; upgrade mise$/);
  assert.equal(await exists(h.out('zsh')), false);
});

test('state that is not schema 2 is ignored and replaced', async (h) => {
  await h.tools({ deno: { version: '2.1.0' } });
  await Deno.mkdir(dirname(h.statePath), { recursive: true });
  await Deno.writeTextFile(h.statePath, '{"schema_version":1,"tools":{"deno":"2.1.0"}}');
  assert.match(await h.run(), /updated: 2/);
  assert.equal((await h.state()).schema_version, 2);
});

const hasZsh = await new Deno.Command('zsh', {
  args: ['-fc', 'true'],
  stdout: 'null',
  stderr: 'null',
})
  .output()
  .then((r) => r.success, () => false);

Deno.test({
  name: 'smoke: a fallback file loads in an isolated zsh through fpath and compinit',
  ignore: !hasZsh,
  fn: async () => {
    const h = await harness();
    try {
      await h.tools({ deno: { version: '2.1.0' } });
      await h.run();
      const script = `fpath=(${h.out('zsh')} $fpath); autoload -Uz compinit; compinit -u -D; ` +
        'print -r -- ${_comps[deno]}';
      const result = await new Deno.Command('zsh', {
        args: ['-fc', script],
        env: { HOME: h.root, ZDOTDIR: h.root },
        stdout: 'piped',
        stderr: 'piped',
      }).output();
      assert.equal(new TextDecoder().decode(result.stdout).trim(), '_deno');
    } finally {
      await h.cleanup();
    }
  },
});
